[YSPARK-202] make HTF take spark versions so it doesn't have to be modified every release

diff --git a/hadooptest/scripts/ci_install_jar b/hadooptest/scripts/ci_install_jar
--- a/hadooptest/scripts/ci_install_jar
+++ b/hadooptest/scripts/ci_install_jar
@@ -21,57 +21,41 @@ then
 fi
 
 # yspark_yarn
-if [ "$1" == "spark12hadoop26" ]
+# allow specifying version if sparkversion parameter used.
+# sparkversion <version number> <optional branch>
+if [ "$1" == "sparkversion" ]
 then
-   if [ ! -d "$WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/share/spark-1.2.0.0_2.6.0.1.1411101121_1412171547" ]
-   then
-      rm -rf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch
-      /usr/local/bin/yinst fetch yspark_yarn-1.2.0.0_2.6.0.1.1411101121_1412171547 -outputfile $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz
-      gunzip -f $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz
-      tar -xf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tar -C $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/
-   fi
+  BRANCH="-br current"
+  rm -rf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch
+  if [[ -z "$2" ]]; then
+    echo "ERROR you must set a spark version"
+    exit 1
+  fi
+  if [[ -n "$3" ]]; then
+    BRANCH="-br $3"
+  fi
+  /usr/local/bin/yinst fetch yspark_yarn-$2 $BRANCH -outputfile $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz
+  gunzip -f $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz
+  tar -xf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tar -C $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/
+elif [ "$1" == "spark14" ]
+then
+  rm -rf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch
+  /usr/local/bin/yinst fetch yspark_yarn-1.4.0.0_2.6.0.16.1506060127_1506241920 -outputfile $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz 
+  gunzip -f $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz
+  tar -xf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tar -C $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/
+elif [ "$1" == "spark15" ]
+then
+  rm -rf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch
+  /usr/local/bin/yinst fetch yspark_yarn-1.5.1.0_2.6.0.16.1506060127_1509251420 -outputfile $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz 
+  gunzip -f $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz
+  tar -xf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tar -C $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/
 else
-   if [ "$1" == "spark12" ]
-   then
-     if [ ! -d "$WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/share/spark-1.2.0.0_2.5.0.8.1411070359_1412171833" ]
-     then
-        rm -rf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch
-        /usr/local/bin/yinst fetch yspark_yarn-1.2.0.0_2.5.0.8.1411070359_1412171833 -outputfile $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz
-        gunzip -f $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz
-        tar -xf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tar -C $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/
-     fi
-   else
-     if [ "$1" == "spark13" ]
-     then
-        rm -rf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch
-        /usr/local/bin/yinst fetch yspark_yarn-1.3.1.0_2.6.0.6.1502061521_1504272233 -outputfile $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz 
-        gunzip -f $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz
-        tar -xf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tar -C $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/
-     else
-       if [ "$1" == "spark14" ]
-       then
-          rm -rf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch
-          /usr/local/bin/yinst fetch yspark_yarn-1.4.0.0_2.6.0.16.1506060127_1506241920 -outputfile $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz 
-          gunzip -f $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz
-          tar -xf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tar -C $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/
-       else
-         if [ "$1" == "spark15" ]
-         then
-            rm -rf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch
-            /usr/local/bin/yinst fetch yspark_yarn-1.5.1.0_2.6.0.16.1506060127_1509251420 -outputfile $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz 
-            gunzip -f $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz
-            tar -xf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tar -C $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/
-         else
-           if [ ! -d "$WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/share/spark-1.2.0.0_2.6.0.1.1411101121_1412171547" ]
-           then
-              rm -rf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch
-              /usr/local/bin/yinst fetch yspark_yarn-1.2.0.0_2.6.0.1.1411101121_1412171547 -outputfile $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz
-              gunzip -f $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz
-              tar -xf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tar -C $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/
-           fi
-         fi
-       fi
-    fi
+  if [ ! -d "$WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/share/spark-1.2.0.0_2.6.0.1.1411101121_1412171547" ]
+  then
+  rm -rf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch
+  /usr/local/bin/yinst fetch yspark_yarn-1.2.0.0_2.6.0.1.1411101121_1412171547 -outputfile $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz
+  gunzip -f $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tgz
+  tar -xf $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/yspark_yarn.tar -C $WORKSPACE/yinst_fetch_dependencies/yspark_yarn_fetch/
   fi
 fi
 
