support noneclustermode and gatewaymode options

diff --git a/hadooptest/scripts/clusterconfig b/hadooptest/scripts/clusterconfig
--- a/hadooptest/scripts/clusterconfig
+++ b/hadooptest/scripts/clusterconfig
@@ -68,6 +68,8 @@
 
 ALWAYS_FETCH_NODES=0
 ALWAYS_BACKUP=0
+NONE_CLUSTER_MODE=0
+GATEWAY_MODE=0
 UPDATE_OPSDB=0
 SHOW_OPSDB=0
 IMAGE=0;
@@ -76,6 +78,7 @@ VALIDATE_RESTORE=0;
 FETCH_NODES_ONLY=0;
 RESTORE=0;
 WORKSPACE_ROOT="$HOME"
+SINGLE_HOST=""
 SSH="/usr/bin/ssh -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
 SCP="/usr/bin/scp -p -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
 OS_VERSION="6.4.1"
@@ -110,7 +113,7 @@ function backupHostDir {
 function usage
 {
     cat <<EOF
-usage: $0  --cluster             |-c <cluster name>
+usage: $0  --cluster             |-c <cluster name> or --noneclustermode
           [--workspace           |-w <workspace directory ]
           [--always_fetch_nodes  |-a ]
           [--always_backup       |-b ]
@@ -127,6 +130,8 @@ usage: $0  --cluster             |-c <cluster name>
 --cluster            Name of the cluster
 --always_fetch_nodes Always fetch nodes from igor (default is false, i.e. don't re-fetch)
 --always_backup      Always backup the keytab files (default is false, i.e. don't backup if it's already been done)
+--noneclustermode    Run script for one off node that is not part of a cluster (e.g. gateway). Requires --node <value>
+--gatewaymode        Run script for all of the flubber cluster gateways.
 --node               Use a temporary alternative node (e.g. to restore a specific node after hardware fixes)
 --nodes              Use temporary alternative nodes list (e.g. to restore specific nodes after hardware fixes)
 --update_opsdb       Update node configuration in opsdb for cluster nodes (default is false)
@@ -166,6 +171,9 @@ $ expecter -n -v ./clusterconfig -c mallard --validate --node fsbl295n19.blue.yg
 $ expecter -n -v ./clusterconfig -c mallard --validate --nodes /tmp/nodes
 $ clusterconfig -w /tmp -c theoden 
 
+# expecter -n -v ./clusterconfig --node gwbl2003.blue.ygrid.yahoo.com --noneclustermode
+# expecter -n -v ./clusterconfig --gatewaymode
+
 Expecter is a wrapper application that provides expect functions
 $ yinst ls -files expecter
 yinst: /home/y/bin/expecter                             expecter-1.0.2
@@ -186,6 +194,10 @@ while [ "$1" != "" ]; do
                                   ;;
         -b | --always_backup )    ALWAYS_BACKUP=1
                                   ;;
+        --noneclustermode )       NONE_CLUSTER_MODE=1
+                                  ;;
+        --gatewaymode )           GATEWAY_MODE=1;
+                                  ;;
         -u | --update_opsdb )     UPDATE_OPSDB=1
                                   ;;
         -s | --show_opsdb )       SHOW_OPSDB=1
@@ -200,6 +212,7 @@ while [ "$1" != "" ]; do
                                   ;;
         -n | --node )             shift
                                   NODE_FILE=/tmp/node.$$;
+                                  SINGLE_HOST=$1;
                                   echo $1 > $NODE_FILE;
                                   UPGRADE_NODES_FILE=$NODE_FILE;
                                   ;;
@@ -218,26 +231,71 @@ while [ "$1" != "" ]; do
     shift
 done
 
+if [[ $NONE_CLUSTER_MODE == 1 ]]; then
+    echo "WARNING: CLUSTER value is not defined. Running in none cluster, single host mode:";
+    if [[ -z $SINGLE_HOST ]]; then
+        echo "ERROR: Required --node value not defined for running with option --noneclustermode!!!";
+        exit 1;
+    fi
+    WORKSPACE="$WORKSPACE_ROOT/cluster-reimage-backup/$SINGLE_HOST"
+else
+    if [[ $GATEWAY_MODE == 1 ]]; then
+        CLUSTER="gateway";
+    fi
 
-if [[ -z $CLUSTER ]]; then
-   echo "ERROR: Required CLUSTER value not defined!!!";
-   exit 1;
+    if [[ -z $CLUSTER ]]; then
+        echo "ERROR: Required CLUSTER value not defined!!!";
+        exit 1;
+    fi
+
+    WORKSPACE="$WORKSPACE_ROOT/cluster-reimage-backup/$CLUSTER"
 fi
 
 #################################################################################
 # Fetch the cluster nodes
 #################################################################################
+if ([[ $ALWAYS_FETCH_NODES == 1 ]] || [[ $ALWAYS_BACKUP == 1 ]]); then
+    set -x
+    rm -rf $WORKSPACE
+    set +x
+fi 
 
-WORKSPACE="$WORKSPACE_ROOT/cluster-reimage-backup/$CLUSTER"
-`/bin/mkdir -p $WORKSPACE`
+set -x
+/bin/mkdir -p $WORKSPACE
+set +x
 
-CLUSTER_NODES="$WORKSPACE/cluster_nodes"
-if ([[ ! -f $CLUSTER_NODES ]] || [[ $ALWAYS_FETCH_NODES == 1 ]]); then
-    echo "Fetch and create the cluster node list file '$CLUSTER_NODES'"
-    `igor fetch -members grid_re.clusters.$CLUSTER > "$CLUSTER_NODES" 2> /dev/null`
-else 
-    echo "Use existing cluster node list file '$CLUSTER_NODES'"
-fi
+# Check cluster backup if CLUSTER is defined
+if [[ -n $CLUSTER ]]; then
+    CLUSTER_NODES="$WORKSPACE/cluster_nodes"
+    if ([[ ! -f $CLUSTER_NODES ]] || [[ $ALWAYS_FETCH_NODES == 1 ]]); then
+        echo "Fetch and create the cluster node list file '$CLUSTER_NODES'"
+        if [[ $GATEWAY_MODE == 1 ]]; then
+            touch $CLUSTER_NODES
+
+            # file=/tmp/gateways; touch $file; for host in `igor list -roles grid_re.clusters.*.gateway`;do echo -n "$host " >> $file; igor fetch -member $host >> $file ; done; 
+            # for gateway in `cut -d" " -f2 /tmp/gateways |sort -u`;do if [[ -z $gateway ]];then continue; fi; echo -n "$gateway "; grep $gateway /tmp/gateways |cut -d"." -f3|tr '\n' ' ';echo;done
+            for host in `igor list -roles grid_re.clusters.*.gateway`;do 
+                echo -n "$host " >> $CLUSTER_NODES ;
+                igor fetch -member $host >> $CLUSTER_NODES ;
+            done;
+        else
+            `igor fetch -members grid_re.clusters.$CLUSTER > "$CLUSTER_NODES" 2> /dev/null`
+        fi
+    else 
+        echo "Use existing cluster node list file '$CLUSTER_NODES'"
+    fi
+
+    if [[ $GATEWAY_MODE == 1 ]]; then
+        for gateway in `cut -d" " -f2 $CLUSTER_NODES |sort -u`;do 
+            if [[ -z $gateway ]];then 
+                continue; 
+            fi;
+            echo -n "$gateway --> ";
+            grep $gateway $CLUSTER_NODES |cut -d"." -f3|tr '\n' ' ';
+            echo;
+        done
+    fi   
+fi 
 
 UPGRADE_NODES_FILE=${UPGRADE_NODES_FILE:="$WORKSPACE/cluster_nodes.upgrade"}
 
@@ -255,11 +313,18 @@ fi
 
 if [[ $FETCH_UPGRADE_NODES == 1 ]]
 then
+    if [[ $GATEWAY_MODE == 1 ]]; then
+        NODES=`cut -d" " -f2 $CLUSTER_NODES |sort -u|sed '/^$/d'`;
+    else
+        NODES=`cat $CLUSTER_NODES`;
+    fi
+
     echo "Fetch and create the upgrade node list file '$UPGRADE_NODES_FILE'"
     # Create the upgrade node file as a record in case there are no nodes that
     # need to be upgraded.
     touch $UPGRADE_NODES_FILE
-    for host in `cat $CLUSTER_NODES`;do
+    # for host in `cat $CLUSTER_NODES`;do
+    for host in $NODES;do
         echo -n "$host: ";
         ver=`$SSH $host cat /etc/redhat-release`;
         CURRENT_OS_STR="current os='$ver'";
@@ -278,7 +343,14 @@ else
 fi
 
 NUM_UPGRADE_NODES=`cat $UPGRADE_NODES_FILE|wc -l`
-echo "Number of nodes to upgrade for cluster '$CLUSTER'='$NUM_UPGRADE_NODES'"
+
+if [[ $NONE_CLUSTER_MODE == 1 ]]; then
+    echo "Number of nodes to upgrade='$NUM_UPGRADE_NODES'"
+elif [[ $GATEWAY_MODE == 1 ]]; then
+    echo "Number of nodes to upgrade for flubber gateways='$NUM_UPGRADE_NODES'"
+else
+    echo "Number of nodes to upgrade for cluster '$CLUSTER'='$NUM_UPGRADE_NODES'"
+fi 
 
 #################################################################################
 # Backup keytabs
