[GRIDCI] - Sync with makerelease changes

diff --git a/deploySupport/insert_bundle_yaml b/deploySupport/insert_bundle_yaml
--- a/deploySupport/insert_bundle_yaml
+++ b/deploySupport/insert_bundle_yaml
@@ -19,6 +19,7 @@ SCRIPT_DIR=`dirname $(readlink -f $0)`
 TS=`date +%s`
 GIT_REPO="git@git.ouroath.com:GridSE/hadoop_releases.git"
 GIT_DIR="$SCRIPT_DIR/hadoop_releases.$TS"
+git config --global push.default matching
 
 component=$1
 # E.g. `date -u +\%Y\%m\%d\%H\%M\%S`
@@ -55,3 +56,9 @@ set +x
 # Update the bundle yaml file
 #################################################################################
 $GIT_DIR/scripts/insert_bundle -component $component -serial $serial -labels $labels -write
+if [ $? -eq 0 ]; then
+  sh -x $GIT_DIR/scripts/update_clusters_ext -cluster axonitered -bundle $component -serial $serial -w
+else
+  echo "FATAL! Unable to update clusters.yaml for -cluster axonitered -bundle $component -serial $serial !!!"
+  exit 1
+fi
